name: Dev to Main

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Backend Dependencies and Run Unit Tests
      working-directory: ./backend
      run: |
        npm install
        npm test

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Run E2E Tests
      working-directory: ./e2e-tests
      run: |
        npm install
        npm test

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Images
      run: |
        docker-compose build
        docker-compose push
