name: Dev to Main

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 Node.js 环境为 22.x
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    # Step 3: 安装后端依赖并运行单元测试
    - name: Install Backend Dependencies and Run Unit Tests
      working-directory: ./backend
      run: |
        npm install
        npm test

    # Step 4: 安装前端依赖并验证构建
    - name: Install Frontend Dependencies and Build
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    # Step 5: 运行端到端测试
    - name: Run E2E Tests
      working-directory: .e2e-tests
      run: |
        npm install
        npm test

    # Step 6: 登录 DockerHub
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 7: 构建和推送 Docker 镜像
    - name: Build and Push Docker Images
      run: |
        docker-compose build
        docker-compose push
