name: Docker Publish

on:
  workflow_dispatch:

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 登录 DockerHub
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: 构建并推送 Docker 镜像
    - name: Build and Push Docker Images
      run: |
        docker-compose build
        docker-compose push
