name: Feature to Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Backend Dependencies and Run Unit Tests
      working-directory: ./backend
      run: |
        npm install
        npm test

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Merge Dev to Main
      uses: devmasx/merge-branch@v2
      with:
        source_branch: dev
        target_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
