name: Node.js CI

on:
  push:
    branches:
      - main
      - dev
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 Node.js 环境为 22.x
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    # Step 3: 安装后端依赖并运行单元测试
    - name: Install Backend Dependencies and Run Unit Tests
      working-directory: ./backend
      run: |
        npm install
        npm test

    # Step 4: 安装前端依赖并运行单元测试
    - name: Install Frontend Dependencies and Run Tests
      working-directory: ./frontend
      run: |
        npm install
        npm test
